"""Engine-neutral protocol, isolated adapters, and deterministic accounting.

These primitives remain deliberately separate from Agent/API and deployment
registration. Product execution is introduced only by the later QE5 slices.
"""

from .protocol import (
    PROTOCOL_NAME,
    SCHEMA_VERSION,
    EngineIdentity,
    ProtocolError,
    build_request,
    canonical_json,
    strict_json_loads,
    validate_request,
    validate_response,
)
from .cn_equity_accounting import (
    CN_EQUITY_LEDGER_SCHEMA,
    CnEquityAccount,
    CnEquityAccountingError,
    CnEquityFeeBreakdown,
    CnEquityFeeSchedule,
    CnEquityLedger,
    CnEquityLedgerEntry,
    CnEquityOrder,
    calculate_cn_equity_fees,
)
from .quantaxis_adapter import (
    QUANTAXIS_ENGINE_COMMIT,
    QUANTAXIS_ENGINE_VERSION,
    QUANTAXIS_SOURCE_SHA256,
    QuantaxisAdapter,
    QuantaxisBacktestEvent,
    QuantaxisBacktestResult,
    QuantaxisBacktestWorkerResult,
    QuantaxisFactorSpec,
    QuantaxisOperationError,
    QuantaxisPositionSnapshot,
    QuantaxisReconciliationError,
    QuantaxisRiskAudit,
    QuantaxisRiskPolicy,
    write_quantaxis_backtest_snapshot,
)
from .runner import RunResult, WorkerConfig, WorkerExecutionError, WorkerRunner, compute_snapshot_sha256

__all__ = [
    "PROTOCOL_NAME",
    "SCHEMA_VERSION",
    "CN_EQUITY_LEDGER_SCHEMA",
    "CnEquityAccount",
    "CnEquityAccountingError",
    "CnEquityFeeBreakdown",
    "CnEquityFeeSchedule",
    "CnEquityLedger",
    "CnEquityLedgerEntry",
    "CnEquityOrder",
    "EngineIdentity",
    "ProtocolError",
    "QUANTAXIS_ENGINE_COMMIT",
    "QUANTAXIS_ENGINE_VERSION",
    "QUANTAXIS_SOURCE_SHA256",
    "QuantaxisAdapter",
    "QuantaxisBacktestEvent",
    "QuantaxisBacktestResult",
    "QuantaxisBacktestWorkerResult",
    "QuantaxisFactorSpec",
    "QuantaxisOperationError",
    "QuantaxisPositionSnapshot",
    "QuantaxisReconciliationError",
    "QuantaxisRiskAudit",
    "QuantaxisRiskPolicy",
    "RunResult",
    "WorkerConfig",
    "WorkerExecutionError",
    "WorkerRunner",
    "build_request",
    "calculate_cn_equity_fees",
    "canonical_json",
    "compute_snapshot_sha256",
    "strict_json_loads",
    "validate_request",
    "validate_response",
    "write_quantaxis_backtest_snapshot",
]
