"""QE4 deterministic StrategySpec DSL and validation boundary."""

from .capabilities import (
    STRATEGY_DSL_VERSION,
    SignalOperator,
    StrategyFieldCapability,
    StrategyFieldKind,
    StrategyFieldSource,
    allowed_operator,
    list_strategy_field_capabilities,
    resolve_strategy_field,
)
from .compiler import (
    STRATEGY_PLAN_VERSION,
    CompiledFieldBinding,
    CompiledStrategyPlan,
    StrategyCompilation,
    compile_strategy_template,
)
from .templates import (
    STRATEGY_TEMPLATE_VERSION,
    FactorThresholdTemplate,
    FactorTrendConfirmationTemplate,
    RebalanceFrequency,
    StrategySourceMode,
    StrategyTemplate,
    StrategyTemplateBuild,
    StrategyTemplateError,
    StrategyTemplateId,
    StrategyTemplateSource,
    ThresholdOperator,
    TopNRebalanceTemplate,
    build_strategy_template,
)
from .validation import (
    StrategyIssueCode,
    StrategySemanticError,
    StrategyValidationIssue,
    StrategyValidationResult,
    require_valid_strategy_spec,
    validate_strategy_spec,
)

__all__ = [
    "STRATEGY_DSL_VERSION",
    "STRATEGY_PLAN_VERSION",
    "STRATEGY_TEMPLATE_VERSION",
    "CompiledFieldBinding",
    "CompiledStrategyPlan",
    "FactorThresholdTemplate",
    "FactorTrendConfirmationTemplate",
    "RebalanceFrequency",
    "SignalOperator",
    "StrategyCompilation",
    "StrategyFieldCapability",
    "StrategyFieldKind",
    "StrategyFieldSource",
    "StrategyIssueCode",
    "StrategySemanticError",
    "StrategySourceMode",
    "StrategyTemplate",
    "StrategyTemplateBuild",
    "StrategyTemplateError",
    "StrategyTemplateId",
    "StrategyTemplateSource",
    "StrategyValidationIssue",
    "StrategyValidationResult",
    "ThresholdOperator",
    "TopNRebalanceTemplate",
    "allowed_operator",
    "build_strategy_template",
    "compile_strategy_template",
    "list_strategy_field_capabilities",
    "require_valid_strategy_spec",
    "resolve_strategy_field",
    "validate_strategy_spec",
]
